package com.yulchon.dao;

import java.util.List;

import com.yulchon.domain.Management;

public interface ManagementDao {
	List<Management> getInventoryList(Management management);
	List<Management> getInvoiceList(Management management);
	boolean insertInvoiceName(Management management);
	Management getRecentInvoice(Management management);
	void syncEzInventoryLotExt(Management management);
	List<Management> getInvoiceInventoryList(Management management);
	boolean insertInvoiceInventory(Management management);
	boolean deleteInvoiceInventory(Management management);
	Management getShippingMarkPrintInventory(Management management);
	boolean insertShippingList(Management management);
	boolean deleteShippingList(Management management);
	List<Management> getShippingList(Management management);
	boolean deleteShippingListInventory(Management management);
	boolean cancelShippingList(Management management);
	boolean cancelInvoiceList(Management management);
	boolean cancelInvoiceInventory(Management management);
	List<Management> getNoUpdatedInvoiceList(Management management);
	boolean updateCustomerProductCodeNumber(Management management);
	boolean insertShippingResult(Management management);
	boolean updateCompleteInvoiceList(Management management);
	List<Management> getCompleteInventoryList(Management management);
	Management mobileGetShippingMarkPrintInventory(Management management);
	boolean deleteNoScanInventory(Management management);
	List<Management> getNoUpdatedOrResetInvoiceList(Management management);
	List<Management> getResetDatas(Management management);
	boolean insertShippingCancel(Management management);
	List<Management> getCancelInventoryList(Management management);
	List<Management> getResetInventoryList(Management management);
	boolean updateInvoiceIsMoved(Management management);
	List<Management> getCustomerList(Management management);
	boolean updateShippingMarkFile(Management management);
	boolean updateCustomerRemark(Management management);
	boolean insertCustomer(Management management);
	List<Management> getShippingDatas(Management management);
	List<Management> getRealDeductInventoryList(Management management);
	boolean updateS_SALES_REQUEST_PROCESS(List<Management> datas);
	Management getSeqSalesRequestInventoryList(Management management);
	boolean updateS_SALES_REQUEST_DETAIL(Management datas);
	boolean updateS_SALES_REQUEST_LOT(List<Management> datas);
	Management getI_ONHAND_INVENTORY(Management management);
	boolean updateI_ONHAND_INVENTORY(Management datas);
	boolean updateI_WH_ONHAND_INVENTORY(Management datas);
	boolean updateI_MONTHLY_INVENTORY(Management datas);
	boolean updateI_WH_MONTHLY_INVENTORY(Management datas);
	Management getI_WH_MONTHLY_INVENTORY(Management management);
	boolean updateI_WH_MONTHLY_INVENTORY2(Management datas);
	List<Management> getI_MONTHLY_INVENTORY(Management management);
	boolean updateI_MONTHLY_INVENTORY2(Management datas);
	boolean updateI_MONTHLY_INVENTORY3(Management datas);
	boolean insertI_TRANSACTION(Management datas);
	boolean insertI_TRANSACTION_DETAIL(Management datas);
	Management getI_TRANSACTION_DETAIL(Management management);
	boolean updateI_TRANSACTION_DETAIL(Management management);
	boolean insertI_TRANSACTION_SALES(Management management);
	Management getProductConfirm(Management management);
	boolean updateInvoiceName(Management management);
	List<Management> getColumnSettingList(Management management);
	boolean insertColumnSetting(Management management);
	boolean deleteColumnSetting(Management management);
	boolean mobileDeleteInvoiceInventory(Management management);
	boolean mobileInsertInvoiceInventory(Management management);
	Management selectI_TRANSACTION_NextSeq(Management management);
	boolean insertS_SALES_REQUEST_LOT(Management management);
	Management selectSEQ_REQUEST_SERIAL(Management management);
	Management getSameWoQtyInventory(Management management);
	boolean swapLotNo(Management datas);
	boolean updateLotNo(Management management);
	Management getIsShippingList(Management management);
	List<Management> getNoShippingMarkCustomerList(Management management);
	
	//출하취소
	List<Management> getCancelShippingList(Management management);
	boolean cancelS_SALES_REQUEST_PROCESS(List<Management> datas);
	boolean cancelS_SALES_REQUEST_LOT(List<Management> datas);
	boolean cancelI_ONHAND_INVENTORY(Management management);
	boolean cancelI_WH_ONHAND_INVENTORY(Management management);
	boolean cancelI_MONTHLY_INVENTORY(Management management);
	boolean cancelI_WH_MONTHLY_INVENTORY(Management management);
	boolean deleteI_TRANSACTION_SALES(Management management);
	boolean deleteI_TRANSACTION_DETAIL(Management management);
	boolean deleteI_TRANSACTION(Management management);
	boolean cancelCompleteInvoiceList(Management management);
	boolean deleteShippingResult(Management management);
	
}
